### ISSUE TITLE
Could we provide a development docker image that is able to build out of box ?

### ISSUE THREAD

**Issue by qingant** [chdb-io/chdb#103]
it takes me a day to setup the build environment and it's  still not working.  Clickhouse provided a `clickhouse/binary-builder` docker images for ci/cd which would also help developer to setup an environment . Wondering if we could do that for chdb.

**Comment by qingant** [comment]
thanks @lmangani 
I tried with `clickhouse/binary-builder`, installed python3-pip, cmake, ninja-build. and run `pip install -U pip setuptools -e .`


then I got this:
```
      CMake Error at contrib/cyrus-sasl-cmake/CMakeLists.txt:79 (target_link_libraries):
        Target "_sasl2" links to:

          ch_contrib::krb5
```

**Comment by lmangani** [comment]
@qingant alright, I'll try to sketch a dedicated chdb docker builder mimicking the action builder and post updates

**Comment by lmangani** [comment]
@qingant the test builder seems to work fine. Could you check and confirm? https://github.com/lmangani/chdb-builder

**Comment by lmangani** [comment]
Repository moved to chdb-io/chdb-builder feel free to open any issue there to continue improving the builder
