### ISSUE TITLE
Feature Request: Iceberg Table Format support

### ISSUE THREAD

**Issue by rakeshJn** [chdb-io/chdb#119]
In Clickhouse, I can query an Iceberg table with a query like this:
`select * from iceberg('https://s3.us-east.cloud-object-storage.appdomain.cloud/lake-sales/tables/sales’, ‘aws_key####’, ‘aws_secret####’, Parquet) limit 2000`

However, when I try the exact same query on chDB, I get this error:

`Code: 46. DB::Exception: Unknown table function Iceberg:  or incorrect parameterized view. (UNKNOWN_FUNCTION)`

Seems like chDB doesn't know iceberg table function.
 P.S, I tried `Iceberg` also (uppercase 'I'), that doesn't work either.

**Comment by lmangani** [comment]
You can see all the supported functions with `SELECT * FROM system.table_functions ORDER BY name` or [here](https://chdb.fly.dev/?user=default#U0VMRUNUICogRlJPTSBzeXN0ZW0udGFibGVfZnVuY3Rpb25zIE9SREVSIEJZIG5hbWU=)

Iceberg support is indeed not currently compiled into chdb. From what I can see the avro dependency must be enabled. 
We'll sure add the dependencies to support the Iceberg table function in the next releases.

**Comment by lmangani** [comment]
Implemented in [v0.15.0](https://chdb.fly.dev/?user=default#U0VMRUNUICogZnJvbSBzeXN0ZW0uZm9ybWF0cyBPUkRFUiBCWSBuYW1l)

**Comment by rakeshJn** [comment]
Thanks!
