### ISSUE TITLE
Update Pypi __version__

### ISSUE THREAD

**Issue by lmangani** [chdb-io/chdb#132]
The current chdb version is not reflected in the pypi package `__version__` on build
```
>>> import chdb
>>> print(chdb.__version__)
0.6.0
>>> chdb.query("SELECT chdb()")
"0.16.0rc2"
```

This does not affect installation and usage, but creates a potentially confusing scenario.

**Comment by auxten** [comment]
Fixed in https://github.com/chdb-io/chdb/commit/6c9b2c6cd0dad0aec798363c2f7de4338d9de426
