### ISSUE TITLE
s3 table function and engine breaks plpython3u (postgresql procedure language extension)

### ISSUE THREAD

**Issue by Iced-Sun** [chdb-io/chdb#139]
**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

```sql
do language plpython3u $$
import chdb
chdb.query(sql='''select * from s3('https://bucket.s3.cn-northwest-1.amazonaws.com.cn/file.parquet') limit 10''')
$$
```

```sql
do language plpython3u $$
import chdb
chdb.query(sql='''
CREATE TABLE s3_engine_table (name String, value UInt32)
    ENGINE=S3('https://clickhouse-public-datasets.s3.amazonaws.com/my-test-bucket-768/test-data.csv.gz', 'CSV', 'gzip')
    SETTINGS input_format_with_names_use_header = 0;
INSERT INTO s3_engine_table VALUES ('one', 1), ('two', 2), ('three', 3);
SELECT * FROM s3_engine_table LIMIT 2;
''')
$$
```

The above queries cause the postgresql server terminated due to segfault. (`server process (PID 1271677) was terminated by signal 6: Aborted;  DETAIL:  Failed process was running: do language plpython3u $$......`)

A `file` table function works just fine.

**Does it reproduce on recent release?**

It reproduces on at v0.15.0

**How to reproduce**

Any s3 related query breaks plpython3u environment by segfault.
 
**Expected behavior**

> A clear and concise description of what you expected to happen.

s3 related query should work with plpython3u.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by lmangani** [comment]
@Iced-Sun did you try the same but using a chdb persistent session? ephemeral queries are on suitable one-shot.
