### ISSUE TITLE
Intergrate with jupysql

### ISSUE THREAD

**Issue by auxten** [chdb-io/chdb#15]
Something like https://jupysql.ploomber.io/en/latest/integrations/duckdb.html
chdb needs a Python DB API 2.0 wrapper to run with jupysql.

**Comment by edublancas** [comment]
@auxten: can chdb use the clickhouse sqlalchemy driver? If so, it should work without changes: https://jupysql.ploomber.io/en/latest/integrations/clickhouse.html

if that doesn't work, we're working on adding support for any driver that follows the DB 2.0 spec

**Comment by auxten** [comment]
Thank you @idomic 
I need to dive into duckdb and [clickhouse-connect](https://github.com/ClickHouse/clickhouse-connect) to see how to do that @edublancas

**Comment by auxten** [comment]
It seems @laodouya is working on the Python DB API 2.0 #30

**Comment by edublancas** [comment]
great! we added support for DB API 2.0 in [Jupysql 0.7.2](https://github.com/ploomber/jupysql/blob/master/CHANGELOG.md#072-2023-04-25)

**Comment by lmangani** [comment]
> great! we added support for DB API 2.0 in [Jupysql 0.7.2](https://github.com/ploomber/jupysql/blob/master/CHANGELOG.md#072-2023-04-25)

If you want you can test the changes ahead or release and provide any feedback: https://github.com/chdb-io/chdb/pull/30
