### ISSUE TITLE
Please make chdb available on conda-forge

### ISSUE THREAD

**Issue by ilyanoskov** [chdb-io/chdb#189]
Dear maintainers,

Thank you very much for this project.
Can you please also make it available on conda-forge? A lot of corporate users cannot install anything via pip, so a conda-forge repo would be very nice.

Kind Regards,
Ilya

**Comment by auxten** [comment]
Sure, I'll try to do it in next week.

**Comment by auxten** [comment]
As chDB only released in bdist on PyPi.
It's impossible to use some auto tools to generate the conda recipe.
And it seems conda-forge didn't support using clang/clang++ on Linux.
And conda-forge will trying to compile chDB from source files, that will be a huge task.

I'm still finding how to do it. Before that, maybe corporate users could download the whl package from the [release page](https://github.com/chdb-io/chdb/releases/tag/v1.2.1) to install chDB in conda env?
