### ISSUE TITLE
Unknown output format MsgPack. (UNKNOWN_FORMAT)

### ISSUE THREAD

**Issue by dchimeno** [chdb-io/chdb#190]
chdb==1.2.0

python 3.9.x

```bash
python -m chdb "select 1,'abc'" MsgPack
```

chdb.__init__.ChdbError: Code: 73. DB::Exception: Unknown output format MsgPack. (UNKNOWN_FORMAT)

**Comment by auxten** [comment]
It's like the issue with the ENABLE compile flag. @nmreadelf happens to be researching related issues. Can you help take a look?
