### ISSUE TITLE
Store database on s3

### ISSUE THREAD

**Issue by igor-kramer** [chdb-io/chdb#244]
It would be great to store chdb database not only on the local disk but on s3/minio/etc.

**Comment by auxten** [comment]
If I understand correctly, you can try the S3 table engine https://clickhouse.com/docs/en/integrations/s3#inserting-data

**Comment by R-omk** [comment]
@auxten   

what about this [Using S3 Plain Rewritable Storage](https://clickhouse.com/docs/en/operations/storing-data#s3-plain-rewritable-storage ) ?

**Comment by auxten** [comment]
Oh, thanks @R-omk. I think the S3 Plain Rewritable Storage should work.
