### ISSUE TITLE
delta format support?

### ISSUE THREAD

**Issue by veinkr** [chdb-io/chdb#248]
I try to use delta to build the data lake and I see the parquet support, wanna ask if the chdb support delta too?

also I searched the clickhouse, and it support to use [deltalake engine](https://clickhouse.com/docs/en/sql-reference/table-functions/deltalake)

If yes, can you help show some sample here?

**Comment by auxten** [comment]
Sure, chDB support [deltalake engine](https://clickhouse.com/docs/en/sql-reference/table-functions/deltalake)
