### ISSUE TITLE
Which clickhouse engines dose chDB currently support and will support in the future

### ISSUE THREAD

**Issue by DanielMao1** [chdb-io/chdb#262]
Hello, I would like to know if there is a list to let me know that, amoung so many engines clickhouse provides, which are supported by chDB? As far as I know, [`Memory` engine has some issues](https://github.com/chdb-io/chdb/issues/197), so I would like to know, which are well supported? (**To be more specific, MergeTree, AggregatingMergeTree, Memory are the three types we are now considering to use, I would like to know if they are supported**) 
## Database engines:
[Atomic](https://clickhouse.com/docs/en/engines/database-engines/atomic)
[Lazy](https://clickhouse.com/docs/en/engines/database-engines/lazy)
[Replicated](https://clickhouse.com/docs/en/engines/database-engines/replicated)
[PostgreSQL](https://clickhouse.com/docs/en/engines/database-engines/postgresql)
[MySQL](https://clickhouse.com/docs/en/engines/database-engines/mysql)
[SQLite](https://clickhouse.com/docs/en/engines/database-engines/sqlite)
[MaterializedPostgreSQL](https://clickhouse.com/docs/en/engines/database-engines/materialized-postgresql)
[MaterializedMySQL](https://clickhouse.com/docs/en/engines/database-engines/materialized-mysql)
## Mergetree engines:
[MergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree)
[Data Replication](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication)
[Custom Partitioning Key](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key)
[ReplacingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree)
[SummingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/summingmergetree)
[AggregatingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/aggregatingmergetree)
[CollapsingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree)
[VersionedCollapsingMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree)
[GraphiteMergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/graphitemergetree)
[Approximate Nearest Neighbor Search Indexes [experimental]](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/annindexes)
[Full-text Indexes](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/invertedindexes)
## Log engines:
[Log](https://clickhouse.com/docs/en/engines/table-engines/log-family/log)
[Stripelog](https://clickhouse.com/docs/en/engines/table-engines/log-family/stripelog)
[TinyLog](https://clickhouse.com/docs/en/engines/table-engines/log-family/tinylog)
## Integration engines:
[Azure Blob Storage](https://clickhouse.com/docs/en/engines/table-engines/integrations/azureBlobStorage)
[DeltaLake](https://clickhouse.com/docs/en/engines/table-engines/integrations/deltalake)
[EmbeddedRocksDB](https://clickhouse.com/docs/en/engines/table-engines/integrations/embedded-rocksdb)
[ExternalDistributed](https://clickhouse.com/docs/en/engines/table-engines/integrations/ExternalDistributed)
[TimeSeries](https://clickhouse.com/docs/en/engines/table-engines/special/time_series)
[HDFS](https://clickhouse.com/docs/en/engines/table-engines/integrations/hdfs)
[Hive](https://clickhouse.com/docs/en/engines/table-engines/integrations/hive)
[Hudi](https://clickhouse.com/docs/en/engines/table-engines/integrations/hudi)
[Iceberg](https://clickhouse.com/docs/en/engines/table-engines/integrations/iceberg)
[JDBC](https://clickhouse.com/docs/en/engines/table-engines/integrations/jdbc)
[Kafka](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka)
[MaterializedPostgreSQL](https://clickhouse.com/docs/en/engines/table-engines/integrations/materialized-postgresql)
[MongoDB](https://clickhouse.com/docs/en/engines/table-engines/integrations/mongodb)
[MySQL](https://clickhouse.com/docs/en/engines/table-engines/integrations/mysql)
[NATS](https://clickhouse.com/docs/en/engines/table-engines/integrations/nats)
[ODBC](https://clickhouse.com/docs/en/engines/table-engines/integrations/odbc)
[PostgreSQL](https://clickhouse.com/docs/en/engines/table-engines/integrations/postgresql)
[RabbitMQ](https://clickhouse.com/docs/en/engines/table-engines/integrations/rabbitmq)
[Redis](https://clickhouse.com/docs/en/engines/table-engines/integrations/redis)
[S3](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3)
[S3Queue](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3queue)
[SQLite](https://clickhouse.com/docs/en/engines/table-engines/integrations/sqlite)
## special engines:
[Distributed](https://clickhouse.com/docs/en/engines/table-engines/special/distributed)
[Dictionary](https://clickhouse.com/docs/en/engines/table-engines/special/dictionary)
[Merge](https://clickhouse.com/docs/en/engines/table-engines/special/merge)
[Executable](https://clickhouse.com/docs/en/engines/table-engines/special/executable)
[File](https://clickhouse.com/docs/en/engines/table-engines/special/file)
[Null](https://clickhouse.com/docs/en/engines/table-engines/special/null)
[Set](https://clickhouse.com/docs/en/engines/table-engines/special/set)
[Join](https://clickhouse.com/docs/en/engines/table-engines/special/join)
[URL](https://clickhouse.com/docs/en/engines/table-engines/special/url)
[View](https://clickhouse.com/docs/en/engines/table-engines/special/view)
[Memory](https://clickhouse.com/docs/en/engines/table-engines/special/memory)
[Buffer](https://clickhouse.com/docs/en/engines/table-engines/special/buffer)
[External Data](https://clickhouse.com/docs/en/engines/table-engines/special/external-data)
[GenerateRandom](https://clickhouse.com/docs/en/engines/table-engines/special/generate)
[KeeperMap](https://clickhouse.com/docs/en/engines/table-engines/special/keeper-map)
[FileLog](https://clickhouse.com/docs/en/engines/table-engines/special/filelog)
> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by auxten** [comment]
Most disk, API, Remote based engine is supported perfectly.
For memory engine, the session problem make it can not persist across query function call. But you can still write all SQL into one query call separated by `;` to make it work.

**Comment by auxten** [comment]
Memory engine is supported. See: https://github.com/chdb-io/chdb/blob/main/tests/test_conn_cursor.py
