### ISSUE TITLE
when using parquet format, data with chinese characters causes error

### ISSUE THREAD

**Issue by yidigo** [chdb-io/chdb#268]
when the data contains chinese characters and i want the result returned in parquet format, it causes something wrong. can someone help me how to solve it ? thanks a lot
![image](https://github.com/user-attachments/assets/b098b671-9e38-4de3-86d1-ed82edb41fed)

**Comment by auxten** [comment]
Python interpreter is saying it can not decode the bytes which is 'Parquet'.
