### ISSUE TITLE
only support pg？can not for greenplum？



### ISSUE THREAD

**Issue by wonb168** [chdb-io/chdb#284]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by auxten** [comment]
AFAIK, pg client can be used to connect greenplum. So, greenplum should be ok

**Comment by wonb168** [comment]
{
	"name": "ChdbError",
	"message": "Code: 36. DB::Exception: Error: ERROR:  column \"attgenerated\" does not exist
LINE 1: ... atttypid as type_id, atttypmod as type_modifier, attgenerat...
                                                             ^
 (in query: SELECT attname AS name, format_type(atttypid, atttypmod) AS type, attnotnull AS not_null, attndims AS dims, atttypid as type_id, atttypmod as type_modifier, attgenerated as generated FROM pg_attribute WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'dim_org_integration' AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'tenant_fastfish_dm')) AND NOT attisdropped AND attnum > 0 ORDER BY attnum ASC). (BAD_ARGUMENTS)",
	"stack": "---------------------------------------------------------------------------
ChdbError                                 Traceback (most recent call last)
File /Users/mac/Library/Mobile Documents/com~apple~CloudDocs/code/python/my_chdb.py:12
      1 #%%    
      2 sql=\"\"\"create table tmp_operating_unit 
      3 ENGINE = MergeTree()
      4 --PRIMARY KEY (brand_code) 
   (...)
     10 group by a.operating_unit_sk,b.brand_code
     11 ;\"\"\"
---> 12 exesql(sql)

File /Users/mac/Library/Mobile Documents/com~apple~CloudDocs/code/python/my_chdb.py:4
      2 def exesql(sql):
      3     print(sql)
----> 4     sess.query(sql)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chdb/session/state.py:47, in Session.query(self, sql, fmt, udf_path)
     43 def query(self, sql, fmt=\"CSV\", udf_path=\"\"):
     44     \"\"\"
     45     Execute a query.
     46     \"\"\"
---> 47     return query(sql, fmt, path=self._path, udf_path=udf_path)

```
File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chdb/__init__.py:78, in query(sql, output_format, path, udf_path)
     76 res = _chdb.query(sql, output_format, path=path, udf_path=g_udf_path)
     77 if res.has_error():
---> 78     raise ChdbError(res.error_message())
     79 return result_func(res)

ChdbError: Code: 36. DB::Exception: Error: ERROR:  column \"attgenerated\" does not exist
LINE 1: ... atttypid as type_id, atttypmod as type_modifier, attgenerat...
                                                             ^
 (in query: SELECT attname AS name, format_type(atttypid, atttypmod) AS type, attnotnull AS not_null, attndims AS dims, atttypid as type_id, atttypmod as type_modifier, attgenerated as generated FROM pg_attribute WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'dim_org_integration' AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'tenant_fastfish_dm')) AND NOT attisdropped AND attnum > 0 ORDER BY attnum ASC). (BAD_ARGUMENTS)"
}
```
need postgres12+?
but gp6 is pg9.4.
