### ISSUE TITLE
Run a query on a pandas dataframe directly

### ISSUE THREAD

**Issue by schalekamp** [chdb-io/chdb#34]
Is there a plan to add the ability to run a sql query directly on a pandas dataframe?
Similar to https://pypi.org/project/sqldf/

```# Import libraries
import pandas as pd
import numpy as np
import chdb

# Create a dummy pd.Dataframe
df = pd.DataFrame({'col1': ['A', 'B', np.NaN, 'C', 'D'], 'col2': ['F', np.NaN, 'G', 'H', 'I']})

# Define a SQL (Clickhouse) query
query = '''
SELECT *
FROM df
WHERE col_1 IS NOT NULL;
'''

# Run the query
df_view = chdb.query(sql, "Dataframe")
```

My current workaround is to 1) save the dataframe to a parquet file and then 2) run chdb.query on that file
I could wrap this into a function that would create a temporary parquet file.
But being able to directly query on dataframes seems very convenient to me.

**Comment by lmangani** [comment]
Not a solution per se, but one possible way to approach this could be latching into the existing stdin/pipe feature of the underlying code from a chdb python object carrying arbitrary data and using the additional flags to define the format, or even the schema of such objects.  Here's a working example of the raw stdin/pipe functionality purely for reference:

```bash
echo -e "1,2\n3,4" | python3 -m chdb "CREATE TABLE table (a Int64, b Int64) ENGINE = File(CSV, stdin); SELECT a + b as sum FROM table; DROP TABLE table" "CSV"
```

**Comment by auxten** [comment]
@alexey-milovidov would you please give us some advice on implementing that?

**Comment by lmangani** [comment]
@auxten updated the above example using the temp table approach and data piping to subprocess. I only tested with CSV but I guess it could work with more complex formats too if anyone wants to try it out.

**Comment by auxten** [comment]
If we want chdb on dataframe running as fast as some `native` SQL on dataframe solution.
We need to let the Clickhouse engine run on the raw memory of dataframe `BlockManager`. I haven't got familiar with the storage engine part of Clickhouse which needs some time.
And also wondering if this feature is really necessary to implement the "hard way".

**Comment by nmreadelf** [comment]
I propose converting a pandas DataFrame into an Apache Arrow table and subsequently reading the Arrow table into ClickHouse

**Comment by lmangani** [comment]
@nmreadelf here's an ArrowStream pipe version

```python
import sys
import pandas as pd
import pyarrow as pa
import chdb
import subprocess

df = pd.DataFrame({'a': [2, 2], 'b': [4, 4]})
# convert Dataframe to Arrow stream
data = pa.BufferOutputStream()
pa.RecordBatchStreamWriter(data, pa.Table.from_pandas(df).schema).write_table(pa.Table.from_pandas(df))
data = data.getvalue()

query = '''
CREATE TABLE table (a Int64, b Int64) ENGINE = File(ArrowStream, stdin); SELECT a + b as sum FROM table;
'''
# Spawn the subprocess and pass custom input from the parent process
def spawn_chdb(query, stdin, format):
    proc = subprocess.Popen(['python3', '-m', 'chdb', query, format], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    custom_input = data
    stdout = proc.communicate(input=stdin)[0].decode('utf-8')
    return stdout

# Call the function to spawn the subprocess with custom input
res = spawn_chdb(query, data, "Dataframe")
# Run the query
print(res)
```

**Comment by auxten** [comment]
A friend also ask me how to continue use chdb on a generated dataframe. It seems important for chdb Python users.

**Comment by jialeiwang** [comment]
As a machine learning algorithm engineer, I need this feature, Here is my scenario:

In data analysis, we often work through a step-by-step iterative process, which involves generating intermediate data tables. These tables allow us to refer back to previous steps and modify or generate new tables as needed. However, the final table we need is often a subset of the intermediate tables. To make things easier, we want to be able to reference the intermediate tables directly by their variable names. Writing out a large SQL query would not be intuitive and could be difficult to read, and changes in the future could be problematic.

If it is necessary to write the intermediate tables to disk, it would be acceptable as long as the user does not perceive this action. For example, the intermediate tables could be stored in a tmpdir and automatically destroyed after use.

**Comment by auxten** [comment]
> @nmreadelf here's an ArrowStream pipe version
> 
> ```python
> import sys
> import pandas as pd
> import pyarrow as pa
> import chdb
> import subprocess
> 
> df = pd.DataFrame({'a': [2, 2], 'b': [4, 4]})
> # convert Dataframe to Arrow stream
> data = pa.BufferOutputStream()
> pa.RecordBatchStreamWriter(data, pa.Table.from_pandas(df).schema).write_table(pa.Table.from_pandas(df))
> data = data.getvalue()
> query = '''
> CREATE TABLE table (a Int64, b Int64) ENGINE = File(ArrowStream, stdin); SELECT a + b as sum FROM table;
> '''
> # Spawn the subprocess and pass custom input from the parent process
> def spawn_chdb(query, stdin, format):
>     proc = subprocess.Popen(['python3', '-m', 'chdb', query, format], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
>     custom_input = data
>     stdout = proc.communicate(input=stdin)[0].decode('utf-8')
>     return stdout
> 
> # Call the function to spawn the subprocess with custom input
> res = spawn_chdb(query, data, "Dataframe")
> # Run the query
> print(res)
> ```
> 
> Perhaps someone more experienced than me could write a wrapper for piping data into queries in a prettier way 😉

Arrow will be a better intermediate data format. There are 2 improvements todo:
1. We can use `INSERT INTO sometable FORMAT ArrowStream` to skip writing table schema.
2. I will find a way to let chdb engine read data from a given fd directly to avoid forking an extra process.

**Comment by lmangani** [comment]
@auxten you're right with Arrow we don't need to define the table columns and the definition can be bypasses. Example updated.

**Comment by auxten** [comment]
I tried different implementations of running chdb on dataframe, the best one is using memfd, See:
https://gist.github.com/auxten/5dd72eeaf5f76728d17531deb59a6dd2

**Comment by nmreadelf** [comment]
> I tried different implementations of running chdb on dataframe, the best one is using memfd, something like:
> 
> ```python
> table = pa.Table.from_pandas(df)
> # create memfd
> fd = os.memfd_create("./tmp_mem_fd", flags=os.MFD_CLOEXEC)
> 
> # create writer from file descriptor
> with pa.RecordBatchStreamWriter(os.fdopen(fd, "wb"), table.schema) as writer:
>     writer.write_table(table)
> 
> os.lseek(fd, 0, os.SEEK_SET)
> 
> # Query with Arrow file descriptor.
> query = f'''CREATE TABLE table ENGINE = File(ArrowStream, {fd});
> SELECT RegionID, SUM(AdvEngineID), COUNT(*) AS c, AVG(ResolutionWidth), COUNT(DISTINCT UserID) 
>     FROM table GROUP BY RegionID ORDER BY c DESC LIMIT 10;'''
> ret = chdb.query(query, output_format="Dataframe")
> os.close(fd)
> ```
> 
> See: https://gist.github.com/auxten/5dd72eeaf5f76728d17531deb59a6dd2

there is an implementation that involves the conversion of a Pandas object to PyArrow within the C++.  https://github.com/duckdb/duckdb/blob/v0.8.0/tools/pythonpkg/src/pyconnection.cpp#L100

**Comment by auxten** [comment]
Also raised issue about pyarrow to_pandas(dtype_backend=pyarrow) https://github.com/apache/arrow/issues/35802
