### ISSUE TITLE
Add arm64 build (and install from source)

### ISSUE THREAD

**Issue by blackrez** [chdb-io/chdb#56]
Hello,

I tried to install chdb on ubuntu arm64 and I've got this error from pip

```
(venv) ubuntu@ip-172-31-31-61:~$ pip install chdb
ERROR: Could not find a version that satisfies the requirement chdb (from versions: none)
ERROR: No matching distribution found for chdb
```

Is it possible to add the source on pypi or arm64 build (or both 😉 )? 

Thanks

**Comment by blackrez** [comment]
Hello @lmangani, 

I use python3.11, if you go to the [file pypi page](https://pypi.org/project/chdb/#files), the source distribution is empty. So if you use a version not supported by binary files it will not work.

**Comment by lmangani** [comment]
You're right we only build arm64 images for OSX at this time. 
On the next major source resync we'll do our best to include Linux arm64 builds. 

If you have some time and compute you can perform a manual build by [following the steps in our action](https://github.com/chdb-io/chdb/blob/main/.github/workflows/build_wheels.yml#L20)

**Comment by auxten** [comment]
> Hello @lmangani,
> 
> I use python3.11, if you go to the [file pypi page](https://pypi.org/project/chdb/#files), the source distribution is empty. So if you use a version not supported by binary files it will not work.

GitHub action did not provide arm64 for macOS or Linux. I have to build the macOS arm64 on my M1 MacBook manually. But sadly, I don't have an arm64 Linux machine.


https://github.com/actions/runner-images/issues/5631

**Comment by blackrez** [comment]
I could give a try on AWS graviton.

**Comment by YoKv** [comment]
is it possible to provide windows build? it make sense to develop desktop application

**Comment by auxten** [comment]
> is it possible to provide windows build? it make sense to develop desktop application

No, ClickHouse doesn't support build on Windows. But you can run ClickHouse on wsl2 which is tested.

**Comment by auxten** [comment]
Trying to fix that #69

**Comment by lmangani** [comment]
Update for @blackrez and anyone else tuned in - arm64 builds for libchdb are now succeeding and we should have (linux) python releases soon!

**Comment by lmangani** [comment]
Great news! arm64/aarch64 builders are now successfully implemented all across:

- chdb python https://github.com/chdb-io/chdb/pull/70 by @nmreadelf 🥳 
- [libchdb](https://github.com/metrico/libchdb) arm64 library packages 📦

**Comment by lmangani** [comment]
@blackrez wheels are out, could you perhaps check and confirm if this works for you? 
https://pypi.org/project/chdb/#files

Thanks!

**Comment by lmangani** [comment]
Tested and Closing as successful. Any input welcome!

```
$ pip install chdb --upgrade --force-reinstall
Collecting chdb
  Obtaining dependency information for chdb from https://files.pythonhosted.org/packages/a8/47/aa128b863773c4f23652a1c088ca12a95e37360332d00ec20152fc49230b/chdb-0.11.4-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
  Downloading chdb-0.11.4-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (11 kB)
Downloading chdb-0.11.4-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (90.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 MB 5.6 MB/s eta 0:00:00
Installing collected packages: chdb
  Attempting uninstall: chdb
    Found existing installation: chdb 0.11.4
    Uninstalling chdb-0.11.4:
      Successfully uninstalled chdb-0.11.4
Successfully installed chdb-0.11.4

$ python3 -m chdb "SELECT version()"
"23.6.1.1"
```

**Comment by blackrez** [comment]
Sorry for the late, but I confirm it works great on AWS graviton. Thank you all for the work.
