### ISSUE TITLE
ChDB fails to execute Query 21 of TPCH_SF10

### ISSUE THREAD

**Issue by reema93jain** [chdb-io/chdb#59]
Hi,

I have been testing ChDB on TPCH_SF10 queries but it fails to execute Query 21. Can you please look into this?
Screenshot below:

![image](https://github.com/chdb-io/chdb/assets/113460610/53d0bf94-a5c2-4e06-a706-de0f90409e06)

Thanks
Reema Jain

**Comment by auxten** [comment]
I have run it successfully with `v0.11.0`, it will consume about 4.5GiB memory. So, how much memory do you get?

result:
```
              supp.S_NAME  numwait
0   b'Supplier#000062538'       24
1   b'Supplier#000032858'       22
2   b'Supplier#000063723'       21
3   b'Supplier#000089484'       21
4   b'Supplier#000007061'       20
..                    ...      ...
95  b'Supplier#000006757'       16
96  b'Supplier#000006795'       16
97  b'Supplier#000006824'       16
98  b'Supplier#000007491'       16
99  b'Supplier#000008301'       16

[100 rows x 2 columns]
```

**Comment by nmreadelf** [comment]
can you provide kernel log, and about your machine information like: cpu, memory size.

run `dmesg` get kernel log.

run `free -m` get memory size.

run `lscpu` get cpu info.

**Comment by nmreadelf** [comment]
my environment: `chdb==0.11.0` `python==3.9.6` I have run it successfully, it consumed a maximum of approximately 10.8 GiB of memory.

```
Out[3]:
              supp.S_NAME  numwait
0   b'Supplier#000062538'       24
1   b'Supplier#000032858'       22
2   b'Supplier#000063723'       21
3   b'Supplier#000089484'       21
4   b'Supplier#000007061'       20
..                    ...      ...
95  b'Supplier#000006757'       16
96  b'Supplier#000006795'       16
97  b'Supplier#000006824'       16
98  b'Supplier#000007491'       16
99  b'Supplier#000008301'       16

[100 rows x 2 columns]
```

**Comment by auxten** [comment]
@reema93jain Can you help confirm it's a memory issue? Maybe also change the comment on Query 21 in PR #58

**Comment by reema93jain** [comment]
Hi Team,

Thank you for looking into it.  

Below are the details about my system. I will remove comment on Query 21:

chdb==0.10.1, Python 3.10.6
![image](https://github.com/chdb-io/chdb/assets/113460610/dc586ffa-2a24-4ff9-a086-5cf7e32654ae)

Memory Size:
![image](https://github.com/chdb-io/chdb/assets/113460610/36e425fc-cea5-41b4-9807-4fa170d2f821)

CPU Info:
![image](https://github.com/chdb-io/chdb/assets/113460610/a0505e72-9b08-4063-8be1-70f

Kernel logs
[kernel_logs.txt](https://github.com/chdb-io/chdb/files/12088145/kernel_logs.txt)
3534a4cdd)

Thanks
Reema Jain
