### ISSUE TITLE
rust support

### ISSUE THREAD

**Issue by web3creator** [chdb-io/chdb#75]
I'm hoping to add support for rust, I'm involved in this, where would I like to start

**Comment by auxten** [comment]
There's a [rust binding](https://github.com/chdb-io/chdb-rust) contributed by the community. I know nothing about rust. Maybe you can:
1. Make an example to show how to use chdb-rust.
2. Implement stateful query just like Python did, you can refer to:
   1. https://github.com/chdb-io/chdb/blob/8db356fe09ad4ae8fd1fd9e7660083eb4f456f09/programs/local/LocalChdb.cpp#L9
   2. https://github.com/chdb-io/chdb/blob/8db356fe09ad4ae8fd1fd9e7660083eb4f456f09/chdb/session/state.py#L34

**Comment by lmangani** [comment]
Hello @web3creator please join the development here: https://github.com/chdb-io/chdb-rust
The binding is already configured, but we need help turning this into a proper crate.
