### ISSUE TITLE
Binary UDF Support

### ISSUE THREAD

**Issue by lmangani** [chdb-io/chdb#80]
ClickHouse patches for [local UDF support](https://github.com/ClickHouse/ClickHouse/pull/52643/files) are now available.
This patch would open up the way for [simple and complex UDF mapping](https://github.com/metrico/libchdb/issues/4)

@auxten can we backport those minor changes to leverage `user_scripts_path` in chdb sessions without a rebase? 

Sketch: https://github.com/chdb-io/chdb/compare/main...UDF-settings

**Comment by auxten** [comment]
Nice, I think the backport branch looks good.

**Comment by lmangani** [comment]
@auxten great! could you cover the function binding into the session handler? I'll then implement in libchdb accordingly.

**Comment by lmangani** [comment]
Required changes have been merged in 0.11.5, so work on this can technically progress forward.
