### ISSUE TITLE
Example of dataframe performance of pandas vs parquet

### ISSUE THREAD

**Issue by danthegoodman1** [chdb-io/chdb#84]
Was looking through the example and saw performance comparing parquet with pandas vs chdb, but it would be interesting to see performance querying dataframes with pandas vs chdb!

**Comment by auxten** [comment]
Benchmark of chDB v2.0.2

<img width="890" alt="image" src="https://github.com/user-attachments/assets/43816954-98a3-4d1c-8a27-1900bac6f508">
