### ISSUE TITLE
cannot import in amazon2 linux

### ISSUE THREAD

**Issue by blackrez** [chdb-io/chdb#90]
**Describe what's wrong**

I'm trying to use chdb on AWS Lambda, I use Docker for testing and building the application. And when I import chdb, it crashed due to clickhouse can't access to /etc/localtime. The file exists, I tried to change the timezone, it failed too.

**How to reproduce**

```
(base) ➜  ~ docker run -d --name chdb --rm public.ecr.aws/lambda/python:3.11
f500dc48b67d268020b2034d92b84f3af7505edcfbce2dc84cb955b296efc13c
docker exec -it chdb /bin/bash
bash-4.2# pip install chdb
Collecting chdb
  Downloading chdb-0.11.5-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (90.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 MB 3.5 MB/s eta 0:00:00
Installing collected packages: chdb
Successfully installed chdb-0.11.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Python 3.11.4 (main, Jul 31 2023, 08:41:59) [GCC 7.3.1 20180712 (Red Hat 7.3.1-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chdb
Poco::Exception. Code: 1000, e.code() = 0, Exception: Cannot load time zone /etc/localtime (version 23.6.1.1)
```

**Comment by lmangani** [comment]
Hello @blackrez interesting. We have a working lambda container running successfully. Could you check out the following links and see if you perhaps can spot a difference between your method and the working one?

- https://github.com/chdb-io/chdb-lambda
- https://github.com/chdb-io/chdb-server/tree/main/lambda

**Comment by auxten** [comment]
Can you help `cat /etc/localtime`. It seems the timezone in this file is not a valid one.
You can also try `mv /etc/localtime /etc/localtime.bak` to see if it works.

**Comment by auxten** [comment]
> For more information about this https://man7.org/linux/man-pages/man5/localtime.5.html. This is a binary file. I just tested with clickhouse local and it didn't work too. I will open a bug in clickhouse.

Yes, but `cat /etc/localtime` will also show many useful info, as the the content on my host shows like this:

```
(chdb311) auxten/chdb [main●] » cat /etc/localtime
TZif�����y��Y^��	�p�ӽ����|@�;>�Ӌ{��B���E"�L���<��fp���A|��R i�� ~��!I}�"g� #)_�$G� %|&'e &�^(G (�@~�p�CDTCSTTZif2
        ����~6C)�������������y������Y^������	�p�����ӽ������������|@�����;>�����Ӌ{������B�������E"�����L�������<������fp�����������A|��R i�� ~��!I}�"g� #)_�$G� %|&'e &�^(G (�@q�~�pLMTCDTCST
CST-8
```

**Comment by nmreadelf** [comment]
hello, you can set TZ environment, on my case:
```bash
bash-4.2# TZ=US/Central python -m chdb 'select version()'
"23.6.1.1"
```

**Comment by nmreadelf** [comment]
i checked TZ environment in `public.ecr.aws/lambda/python:3.11`.
```bash
bash-4.2# echo $TZ
:/etc/localtime
```
the normal TZ environment value format should be {country}/{city}. e.g: `TZ=US/Central`

it seens TZ environment value problem, another solution is unset TZ environment. my case :
```bash
bash-4.2# unset TZ
bash-4.2# python -m chdb 'select version()'
"23.6.1.1"
```

**Comment by lmangani** [comment]
@blackrez can we mark this as resolved with the suggestions, or are you still experiencing issues?

**Comment by blackrez** [comment]
Hello, it is fixed.
