### ISSUE TITLE
Example on how to query pyarrow table

### ISSUE THREAD

**Issue by danthegoodman1** [chdb-io/chdb#93]
The example for section `Query On Table (Pandas DataFrame, Parquet file/bytes, Arrow bytes)` on the readme has a dataframe example, but not pyarrow.

Also, question: is it zero-copy select?

**Comment by danthegoodman1** [comment]
Bonus points for showing how to make it a virtual table with another name: `ret_tbl = cdf.query(sql='select * from __tb1__', tb1=cdf.Table(arrow_table=arw))`

**Comment by auxten** [comment]
I will try to make chdb.dataframe just in chdb package.
This way we could also query dataframe in chdb Session.

**Comment by auxten** [comment]
New chDB 2.0 API of query on ArrowTalbe: https://github.com/chdb-io/chdb/blob/d990ff80a54f5bf60ecea94d8cff8ec1f12c1d94/tests/test_query_py.py#L94
